apiVersion: v3
name: sample-app
description: A Helm chart for Kubernetes

type: application

version: 0.1.1


appVersion: 1.0.0


# ---
# apiVersion: v2
# name: test
# description: A Helm chart for Kubernetes
# type: application
# version: 0.1.0

dependencies:
  - name: helm-master
    version: "^1.0.6-SNAPSHOT"
    repository: "https://luismiguelzapata.github.io/helm-repository/"
