apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-common-chart
  namespace: argocd
spec: 
  generators:
    - git:
        repoURL: https://github.com/luismiguelzapata/ArgoCD-ApplicationSet-Demo.git
        revision: HEAD
        directories:
          # here it will read the paths under configs and the subpaths under the config paths
          - path: matrix/*/*/*/*
          #- path: matrix/*/providers/*/*
          - path: matrix/templates/*
            exclude: true
          - path: matrix/appset
            exclude: true
          # - path: matrix/*/env
          #   exclude: true
          #- path: matrix/*/env/*
          #- path: matrix/*/provider/*
        
  template:
    metadata:
      namespace: argocd
      # you can use the path strings with / delimiter as variables
      #name: "{{path[1]}}-{{path.basename}}"
      name: "{{path[1]}}-{{path[2]}}-{{path.basename}}"
    spec:
      project: default
      source:
        helm:
          # specify different values file based on directories variables
          valueFiles:
            # - "{{path[1]}}/{{path.basename}}/values.yaml"
            # - "{{path[1]}}/values.yaml" 
            - "{{path[1]}}/{{path[2]}}/values.yaml"
            - "{{path[1]}}/{{path[2]}}/providers//{{path.basename}}/values.yaml"
        path: matrix
        repoURL: https://github.com/luismiguelzapata/ArgoCD-ApplicationSet-Demo.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
      destination:
        # specify different destinations
        namespace: "{{path[2]}}-ns"
        server: https://kubernetes.default.svc
