apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-helm-common-chart
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/luismiguelzapata/ArgoCD-ApplicationSet-Demo.git
        revision: HEAD
        directories:
          # here it will read the paths under configs and the subpaths under the config paths
          - path: demo/configs/*/*
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  deploy: "yes" # label que indicamos para que solamente genere las apps de los clusters que existen
          - git:
              repoURL: https://github.com/luismiguelzapata/ArgoCD-ApplicationSet-Demo.git
              revision: HEAD
              directories:
              - path: 'demo/configs/*'
  template:
    metadata:
      namespace: argocd
      # you can use the path strings with / delimiter as variables
      name: "{{path[3]}}-{{path.basename}}"
    spec:
      project: default
      source:
        helm:
          # specify different values file based on directories variables
          valueFiles:
            - "configs/{{path[2]}}/{{path.basename}}/values.yaml"
            - "configs/{{path[2]}}/values.yaml" 
        path: demo
        repoURL: https://github.com/luismiguelzapata/ArgoCD-ApplicationSet-Demo.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
      destination:
        server: '{{metadata.annotations.server}}'
        namespace: '{{path[2]}}/{{path.basename}}'
      destination:
        # specify different destinations
        namespace: "{{path[2]}}/{{path.basename}}"
        server: https://kubernetes.default.svc
