apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{path[1]}}-{{path[2]}}-{{path.basename}}-settings"
data:
  settings.ini: |
    # possible values : production, development, staging, qa
    app_mode = {{ .Values.appMode }}

    [security]
    # Path to SSL certificates
    certificates = {{ .Values.certificatePath }}

    [paypal]
    paypal_url = {{ .Values.paypalURLLocation }}

    [mysql]
    db_user = {{ .Values.databaseUser }}
    db_password = {{ .Values.databasePassword }}



